# Generated by Django 4.2 on 2023-04-20 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('number', models.IntegerField(max_length=2)),
                ('row_num', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('type_hive', models.CharField(blank=True, choices=[('rut', 'Рут'), ('dad', 'Дадан'), ('old', 'Лежак'), ('n-1', 'Нук'), ('n-2', 'Нук 2М'), ('n-3', 'Нук 3М'), ('n-4', 'Нук 4М'), ('xxx', 'XNYA')], default='rut', max_length=3)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('volume', models.CharField(blank=True, choices=[('0', 'Меньше 10 рамок'), ('1', '1 корпус'), ('2', '2 корпуса'), ('3', '3 корпуса'), ('4', '4 корпуса'), ('5', '5 корпусов!!!')], default=1, max_length=1)),
                ('pub_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('beehive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bee.beehive')),
            ],
        ),
        migrations.AddField(
            model_name='beehive',
            name='queen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bee.queen'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('beehive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bee.beehive')),
            ],
        ),
    ]
