# Generated by Django 4.2 on 2023-04-22 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beehive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(max_length=1000, verbose_name='Описание')),
                ('type_hive', models.CharField(blank=True, choices=[('rut', 'Рут'), ('dad', 'Дадан'), ('old', 'Лежак'), ('n-1', 'Нук'), ('n-2', 'Нук 2М'), ('n-3', 'Нук 3М'), ('n-4', 'Нук 4М'), ('xxx', 'XNYA')], default='rut', max_length=3, verbose_name='Тип улья')),
                ('is_active', models.BooleanField(default=True)),
                ('volume', models.CharField(blank=True, choices=[('0', 'Меньше 10 рамок'), ('1', '1 корпус'), ('2', '2 корпуса'), ('3', '3 корпуса'), ('4', '4 корпуса'), ('5', '5 корпусов!!!')], default=1, max_length=1, verbose_name='К-во корпусов')),
                ('pub_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год рождения')),
                ('title', models.CharField(max_length=100, verbose_name='Порода')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('post_date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('is_active', models.BooleanField(default=True)),
                ('beehive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bee.beehive', verbose_name='Улей')),
            ],
        ),
        migrations.AddField(
            model_name='beehive',
            name='queen',
            field=models.ForeignKey(blank=True, help_text='Матка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bee.queen', verbose_name='Матка'),
        ),
        migrations.AddField(
            model_name='beehive',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bee.row', verbose_name='Ряд'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Действие')),
                ('post_date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('beehive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bee.beehive', verbose_name='Улей')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
