# Generated by Django 4.2 on 2023-04-30 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-post_date', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-is_active', 'post_date']},
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('post_date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('beehive', models.ManyToManyField(to='bee.beehive', verbose_name='ПС')),
            ],
        ),
    ]
